spring.application.name=notecurve

# MySQL 연결 정보
#spring.datasource.url=jdbc:mysql://host.docker.internal:3306/notecurve_db?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.url=jdbc:mysql://10.0.0.6:3306/notecurve_db?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT 설정
jwt.secret=${JWT_SECRET_KEY}

# 업로드 경로
file.upload-dir=/app/uploads/images
note.upload-dir=/app/uploads/notes
profile.upload-dir=/app/uploads/profiles

# 파일 업로드 크기 제한
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

# API Key
itletter.api-key=${ITLETTER_API_KEY}
